version: "3.8"
services:  
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'
    restart: always

  server:
    build: .
    ports:
      - "80:5000"
    restart: always
    depends_on:
      - mongodb

volumes:
  data:
